jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Setup Rclone action
      uses: AnimMouse/setup-rclone@v1
      with:
        rclone_config: ${{ secrets.RCLONE_CONFIG }}
    - name: Get package name
      run: |
       PKGNAME=`curl "https://raw.githubusercontent.com/YidaozhanYa/arch-build/main/pkgname.txt" | head -1`
       echo "PKGNAME=${PKGNAME}" >> $GITHUB_ENV
    - uses: Brx86/build-aur-action@yay
      with:
        pkgname: ${{ env.PKGNAME }}
    - name: Upload package
      env:
        PKGNAME: ${{ env.PKGNAME }}
      run: |
       PACKAGES=`ls ./${PKGNAME}`
       for package in $PACKAGES
       do
        rclone copy ./${PKGNAME}/${package} e5:/pkgbuild/x86_64
       done
    - uses: YidaozhanYa/update-db-for-repo@master
      with:
        tag: x86_64
    - name: Upload generated database
      run: |
       ls
       pwd
       export GODEBUG=asyncpreemptoff=1 
       mkdir -p database
       cp ./yidaozhan.* database
       rclone copy ./database/yidaozhan.db e5:/pkgbuild/x86_64
       rclone copy ./database/yidaozhan.db.tar.gz e5:/pkgbuild/x86_64
       rclone copy ./database/yidaozhan.db.tar.gz.old e5:/pkgbuild/x86_64
       rclone copy ./database/yidaozhan.files e5:/pkgbuild/x86_64
       rclone copy ./database/yidaozhan.files.tar.gz e5:/pkgbuild/x86_64
       rclone copy ./database/yidaozhan.files.tar.gz.old e5:/pkgbuild/x86_64
name: build-aur-one
on:
  push:
    paths:
      - 'pkgname.txt'
      - '.github/workflows/build-aur-one.yml'
  workflow_dispatch: null
